name: Notify on README change in Examples

on:
  push:
    paths:
      - 'examples/**/readme.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get changed files
        id: changes
        run: |
          echo "files=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep 'examples/.*/readme.md')" >> "$GITHUB_OUTPUT"

      - name: Notify Telegram if README changed
        if: steps.changes.outputs.files != ''
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          CHANGES=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep 'examples/.*/readme.md')
          MESSAGE="📁 Обновления в Examples/readme.md:%0A"
          while read -r line; do
            STATUS=$(echo "$line" | awk '{print $1}')
            FILE=$(echo "$line" | awk '{print $2}')
            case $STATUS in
              A) MESSAGE+="➕ Добавлен: $FILE%0A" ;;
              M) MESSAGE+="✏️ Изменён: $FILE%0A" ;;
              D) MESSAGE+="❌ Удалён: $FILE%0A" ;;
              *) MESSAGE+="📄 $STATUS: $FILE%0A" ;;
            esac
          done <<< "$CHANGES"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE"
