name: Notify on README change in Examples

on:
  push:
    paths:
      - 'Examples/**/README.md'
      - 'examples/**/readme.md'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changes
        run: |
          CHANGES=$(git diff --name-status HEAD^ HEAD | grep -i 'examples/.*/readme.md' || true)
          echo "files=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Notify Telegram if README changed
        if: steps.changes.outputs.files != ''
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          CHANGES=$(git diff --name-status HEAD^ HEAD | grep -i 'examples/.*/readme.md' || true)
          MESSAGE="📁 Updates in Examples:%0A"
          while read -r line; do
            STATUS=$(echo "$line" | awk '{print $1}')
            FILE=$(echo "$line" | awk '{print $2}')
            case $STATUS in
              A) MESSAGE+="➕ Added: $FILE%0A" ;;
              M) MESSAGE+="✏️ Edited: $FILE%0A" ;;
              D) MESSAGE+="❌ Deleted: $FILE%0A" ;;
              *) MESSAGE+="📄 $STATUS: $FILE%0A" ;;
            esac
          done <<< "$CHANGES"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE"
