name: Notify on README change in Examples

on:
  push: # запускается на любой пуш
    branches:
      - main  # или твоя ветка

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed README files
        id: changes
        run: |
          CHANGES=$(git diff --name-status HEAD^ HEAD | grep -iE '^Examples/.+/README\.md$' || true)
          echo "files=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Notify Telegram if README changed
        if: steps.changes.outputs.files != ''
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          CHANGES=$(git diff --name-status HEAD^ HEAD | grep -iE '^Examples/.+/README\.md$' || true)
          MESSAGE="📁 Обновления в Examples/README.md:%0A"
          while read -r line; do
            STATUS=$(echo "$line" | awk '{print $1}')
            FILE=$(echo "$line" | awk '{print $2}')
            case $STATUS in
              A) MESSAGE+="➕ Добавлен: $FILE%0A" ;;
              M) MESSAGE+="✏️ Изменён: $FILE%0A" ;;
              D) MESSAGE+="❌ Удалён: $FILE%0A" ;;
              *) MESSAGE+="📄 $STATUS: $FILE%0A" ;;
            esac
          done <<< "$CHANGES"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE"
